# Generated by Django 5.2.1 on 2025-05-29 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_vehicletype_alter_booking_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='vehicle_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='client.vehicletype'),
        ),
        migrations.AlterField(
            model_name='vehicletype',
            name='type_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
